---
- hosts: "{{ passed_in_hosts }}"
  become: True
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: update yum
      yum:
        update_cache: true
        update_only: true
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      systemd:
        name: httpd
        enabled: True
        state: started